function ori = RT605_FK_Orientation(q1,q2,q3,q4,q5,q6)
%RT605_FK_ORIENTATION
%    ORI = RT605_FK_ORIENTATION(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-May-2021 21:11:51

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = t3.*t4;
t15 = t3.*t10;
t16 = t4.*t9;
t17 = t9.*t10;
t18 = t8.*t17;
t19 = -t17;
t20 = t2.*t14;
t21 = t8.*t14;
t22 = t2.*t17;
t25 = t15+t16;
t23 = -t21;
t24 = t2.*t19;
t26 = t14+t19;
t27 = t5.*t6.*t25;
t28 = t11.*t13.*t25;
t29 = t12.*t26;
t30 = t20+t24;
t31 = t18+t23;
t32 = -t28;
t33 = t28.*1i;
t34 = t27+t29;
t35 = t7.*t34;
t36 = t35.*1i;
t38 = t32+t35;
t39 = (t28-t35).^2;
t37 = -t36;
t40 = -t39;
t41 = t40+1.0;
t42 = sqrt(t41);
ori = [atan2(-t13.*t34-t7.*t11.*t25,-t6.*t26+t5.*t12.*t25),angle(t33+t37+t42),angle(t33+t37-t42),atan2(-t7.*(t6.*(t2.*t11+t5.*t31)+t12.*(t8.*t15+t8.*t16))-t13.*(t2.*t5-t11.*t31),-t7.*(t12.*(t2.*t15+t2.*t16)-t6.*(t8.*t11+t5.*t30))+t13.*(t5.*t8-t11.*t30))];
